### ISSUE TITLE
As a deployer I'd like to have all configuration values in one place

### ISSUE THREAD

**Issue by alon-e** [iota-community/one-command-tangle#1]
in the current state, values are duplicated on the different components.
so changing `mwm` for example, requires changing 2 lines, this can lead to mistakes.

It would be great to extract the variables to a config file (similar to https://github.com/iotaledger/compass/blob/master/docs/private_tangle/config.example.json)
or move them to the top of the yml file and have them declared once.

**Comment by fijter** [comment]
The most basic configuration options for the core of the one command tangle were added to a `.env` file and are used in docker-compose. There is no need any more to modify `docker-compose.yml` manually now, unless you wish to do something a bit more exotic.
